version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eml-parser-api-prod
    env_file:
      - .env # Use the same .env file, or a dedicated .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
    restart: unless-stopped
    networks:
      - app-network-prod
    # Note: No volume mount for code in production

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-prod
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
    restart: unless-stopped
    networks:
      - app-network-prod
    # In a real production scenario, this collector would be configured
    # to export to a managed service like Datadog, Honeycomb, etc.

networks:
  app-network-prod:
    driver: bridge
