"""Create parsed_emails and raw_emails tables

Revision ID: e37a13e05184
Revises: 
Create Date: 2025-10-02 16:26:21.982457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37a13e05184'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sender_ip', sa.String(), nullable=True),
    sa.Column('ollama_evaluation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_emails_from_address'), 'parsed_emails', ['from_address'], unique=False)
    op.create_index(op.f('ix_parsed_emails_id'), 'parsed_emails', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_emails_subject'), 'parsed_emails', ['subject'], unique=False)
    op.create_index(op.f('ix_parsed_emails_to_address'), 'parsed_emails', ['to_address'], unique=False)
    op.create_table('raw_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('parsed_email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parsed_email_id'], ['parsed_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_emails_id'), 'raw_emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_emails_id'), table_name='raw_emails')
    op.drop_table('raw_emails')
    op.drop_index(op.f('ix_parsed_emails_to_address'), table_name='parsed_emails')
    op.drop_index(op.f('ix_parsed_emails_subject'), table_name='parsed_emails')
    op.drop_index(op.f('ix_parsed_emails_id'), table_name='parsed_emails')
    op.drop_index(op.f('ix_parsed_emails_from_address'), table_name='parsed_emails')
    op.drop_table('parsed_emails')
    # ### end Alembic commands ###
